Ya-a-a-ay, inheritance.
CPP-KT/cpp-notes pull request #23
Opened 2022-06-28 14:56 UTC by 334905

2022-06-28 15:23 UTC, lejabque requested changes

2022-06-28 15:23 UTC, lejabque commented on src/08_inheritance.md
> +Во-первых, **не надо наследоваться, если вам нужно только расширить класс**. Если вы добавить новый функционал в `std::string`, не нужно от него наследоваться, а то ваш коллега тоже захочет по-другом
давай чуть менее агрессивный стиль, без "потому что вы научились"

2022-06-28 15:23 UTC, lejabque commented on src/08_inheritance.md
> +Это выглядит как шизофрения, ей и является, но это пока пример простой выглядит идиотски. К тому же, у этого есть вторая проблема — вот сделали вы `string_printer("Hello, world").print()`. А что если
>Это выглядит как шизофрения, ей и является, но это пока пример простой выглядит идиотски.
ну и это тоже не нужно)

2022-06-28 15:36 UTC, 334905 commented on src/08_inheritance.md
> +Это выглядит как шизофрения, ей и является, но это пока пример простой выглядит идиотски. К тому же, у этого есть вторая проблема — вот сделали вы `string_printer("Hello, world").print()`. А что если
Fixed.

2022-06-28 15:36 UTC, 334905 commented on src/08_inheritance.md
> +Во-первых, **не надо наследоваться, если вам нужно только расширить класс**. Если вы добавить новый функционал в `std::string`, не нужно от него наследоваться, а то ваш коллега тоже захочет по-другом
Fixed.

2022-06-29 19:06 UTC, lejabque approved these changes

2022-06-29 19:06 UTC, merged