added some examples and fixed typos
CPP-KT/cpp-notes pull request #34
Opened 2023-06-25 14:20 UTC by murysinm

2023-06-27 09:02 UTC, dedlocc requested changes

2023-06-27 09:02 UTC, dedlocc commented on src/01_asm.md
> +- наличие `red zone` (например, она есть на 64-битных линуксах)
Везде с заглавной, тут со строчной

2023-06-27 09:02 UTC, dedlocc commented on src/01_asm.md
> +Что такое `red zone`? Это кусок памяти ниже указателя стека, который никто, кроме нас, не имеет права использовать. На 64-битных линуксах размер этого куска - 128 байт. То есть можно безопасно исполь
`-` &mdash; не тире

2023-06-27 09:02 UTC, dedlocc commented on src/01_asm.md
> +Заметим, что на Windows, например, `red zone`'ы нет.
Это правда только для x86

2023-06-27 09:02 UTC, dedlocc commented on src/01_asm.md
> +Что такое `red zone`? Это кусок памяти ниже указателя стека, который никто, кроме нас, не имеет права использовать. На 64-битных линуксах размер этого куска - 128 байт. То есть можно безопасно исполь
Я бы по этому описанию не понял, в чём проблема писать ниже стека

2023-06-27 09:02 UTC, dedlocc commented on src/04_syntax_types.md
> +Есть еще обычный `enum`, без слова `class`. Это тип-перечисление, который пришел из Си. Но им лучше не пользоваться, потому что:
Пожалуйста, ставь `ё` (ещё, пришёл), в других местах тоже

2023-06-27 09:02 UTC, dedlocc commented on src/04_syntax_types.md
> + - у `enum` не прописано, какой внутри тип внутри (underlying type). Причём, не прописано именно в стандарте. То есть, это может отличаться от компилятора к компилятору.
Возможно лучше написать про то, что такое underlying type, ещё выше, в части про `enum class`. Странно это понятие вводить только тут.

Ещё тут опечатка: "какой внутри тип внутри"

2023-06-27 09:02 UTC, dedlocc commented on src/04_syntax_types.md
> + - у `enum` не прописано, какой внутри тип внутри (underlying type). Причём, не прописано именно в стандарте. То есть, это может отличаться от компилятора к компилятору.
Опять же, насколько я вижу, в остальном тексте в перечислениях первое слово начинается с большой буквы. Давай поддерживать единый стиль.

2023-06-27 09:02 UTC, dedlocc commented on src/04_syntax_types.md
> + - у `enum` не прописано, какой внутри тип внутри (underlying type). Причём, не прописано именно в стандарте. То есть, это может отличаться от компилятора к компилятору.
"Причём" &mdash; не вводное слово и не обособляется. "То есть" &mdash; тоже.

2023-06-27 09:02 UTC, dedlocc commented on src/04_syntax_types.md
> +	```
Зачем тут табуляция?

2023-06-27 09:02 UTC, dedlocc commented on src/04_syntax_types.md
> +А еще есть *функция `alignof`*.	Она возвращает *выравнивание* структуры. *Выравнивание* структуры - это число, на которое должен делиться тот адрес, по которому мы размещаем структуру. Использование:
Раз уж приводишь примеры использования, можно написать про то, что их можно применять и к значениям

2023-06-27 09:02 UTC, dedlocc commented on src/07_inheritance.md
> +А почему `base b = d;` - не ошибка компиляции?
Тире (не буду писать везде)

2023-06-27 09:02 UTC, dedlocc commented on src/07_inheritance.md
> +И самом деле у нас написано такое:
Тут явно опечатка

2023-06-27 09:02 UTC, dedlocc commented on src/07_inheritance.md
> +На самом деле внутри base компилятор сгенерировал конструктор копирования.
`base`

2023-06-27 09:02 UTC, dedlocc commented on src/07_inheritance.md
> +Так что тут у нас просто скопировались те мемберы, которые можно было скопировать, а мемберы `derived`'а потерялись.
"которые можно было скопировать" &mdash; лучше пояснить/переформулировать

2023-06-27 09:02 UTC, dedlocc commented on src/07_inheritance.md
> +Это называется **slicing**.
"Object slicing", если быть точнее

2023-06-27 09:02 UTC, dedlocc commented on src/07_inheritance.md
> +Кстати, у `derived`'а удалять эти функции уже не обязательно, они не сгенерятся, если у `base`'а удалены.
Я не увидел ответа на вопрос "как избежать slicing'а"

2023-06-27 09:02 UTC, dedlocc commented on src/08_exceptions.md
> +	**Unwinder** - раскручиватель стека. (мы у него можем спросить: вот если я сейчас сделаю `return`, то где я окажусь?). Когда летит исключение, надо понимать, откуда вызвана функция. Поэтому использу
Не нужна точка перед скобкой

2023-06-27 09:02 UTC, dedlocc commented on src/08_exceptions.md
> +	**Unwinder** - раскручиватель стека. (мы у него можем спросить: вот если я сейчас сделаю `return`, то где я окажусь?). Когда летит исключение, надо понимать, откуда вызвана функция. Поэтому использу
Я бы первое предложение слепил со третьим. Так порядок мыслей какой-то странный.

2023-06-27 09:02 UTC, dedlocc commented on src/08_exceptions.md
> +	Но C++ такой фичи не имеет, но в реализации это всё равно есть.
Но... но

2023-06-27 09:02 UTC, dedlocc commented on src/08_exceptions.md
> +	Это тоже лишняя сложность - на самом деле стэк раскручивается дважды: один раз для того, чтобы найти `catch`, в который мы попали и узнать, *resume*'ящийся он или нет, а потом уже можно раскрутить к
Проблемы с пунктуацией

2023-06-27 09:02 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +void bad()
У меня тут вопросы к расстановке переносов строк

2023-06-27 09:02 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +- может быть, если компилятор вообще не упрощает код, переменная реально изменится
ditto про перечисления

2023-06-27 09:02 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +- если код требует этих ключиков, то он, скорее всего, сломанный. Такое лучше написать как-то иначе.
Какое "такое"?

2023-06-27 09:02 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +- эти ключики подавляют оптимизации компилятора. Например, компилятор не сможет делать те оптимизации, которые делал, когда обсуждался `strict-aliasing`.
Почему "например"? Это связано с какими-то другими оптимизациями?

2023-06-27 09:02 UTC, dedlocc commented on src/12_validation.md
> +`+` **хорошо взаимодействует с отладчиками** - отладчики умеют показывать место, где упала программа. Например, linux умеет создать дамп своей памяти перед `std::abort`, и в отладчике можно посмотрет
"умеет создать"

2023-06-27 09:02 UTC, dedlocc commented on src/12_validation.md
> +Cто́ит ли давать программу с `assert`'ами пользователю? Если вы задались этим вопросом, скорее всего у вас недостаточно  `assert`'ов в программе, ведь когда их достаточно, программа замедляется раза
2 пробела

2023-06-27 09:14 UTC, murysinm commented on src/01_asm.md
> +- наличие `red zone` (например, она есть на 64-битных линуксах)
fixed

2023-06-27 09:21 UTC, murysinm commented on src/01_asm.md
> +Заметим, что на Windows, например, `red zone`'ы нет.
fixed, заменил на `... на x86 Windows ...`

2023-06-27 09:54 UTC, murysinm commented on src/12_validation.md
> +Cто́ит ли давать программу с `assert`'ами пользователю? Если вы задались этим вопросом, скорее всего у вас недостаточно  `assert`'ов в программе, ведь когда их достаточно, программа замедляется раза
fixed

2023-06-27 09:55 UTC, murysinm commented on src/01_asm.md
> +Что такое `red zone`? Это кусок памяти ниже указателя стека, который никто, кроме нас, не имеет права использовать. На 64-битных линуксах размер этого куска - 128 байт. То есть можно безопасно исполь
починил везде

2023-06-27 11:19 UTC, murysinm commented on src/01_asm.md
> +Что такое `red zone`? Это кусок памяти ниже указателя стека, который никто, кроме нас, не имеет права использовать. На 64-битных линуксах размер этого куска - 128 байт. То есть можно безопасно исполь
добавил информацию про это

2023-06-27 11:41 UTC, murysinm commented on src/11_undefined_behaviour.md
> +void bad()
если я правильно понял, что не так, то fixed: убрал лишние переводы строк

2023-06-27 11:41 UTC, murysinm commented on src/11_undefined_behaviour.md
> +- может быть, если компилятор вообще не упрощает код, переменная реально изменится
fixed

2023-06-27 11:42 UTC, murysinm commented on src/08_exceptions.md
> +	Это тоже лишняя сложность - на самом деле стэк раскручивается дважды: один раз для того, чтобы найти `catch`, в который мы попали и узнать, *resume*'ящийся он или нет, а потом уже можно раскрутить к
чуть-чуть поменял это место и исправил проблемы с пунктуацией

2023-06-27 11:42 UTC, murysinm commented on src/08_exceptions.md
> +	Но C++ такой фичи не имеет, но в реализации это всё равно есть.
fixed

2023-06-27 11:42 UTC, murysinm commented on src/07_inheritance.md
> +Это называется **slicing**.
fixed

2023-06-27 11:42 UTC, murysinm commented on src/07_inheritance.md
> +На самом деле внутри base компилятор сгенерировал конструктор копирования.
fixed

2023-06-27 11:43 UTC, murysinm commented on src/07_inheritance.md
> +И самом деле у нас написано такое:
fixed

2023-06-27 11:43 UTC, murysinm commented on src/04_syntax_types.md
> +	```
убрал

2023-06-27 11:58 UTC, murysinm commented on src/11_undefined_behaviour.md
> +- эти ключики подавляют оптимизации компилятора. Например, компилятор не сможет делать те оптимизации, которые делал, когда обсуждался `strict-aliasing`.
немного переписал это предложение, чтобы было понятнее

2023-06-27 11:58 UTC, murysinm commented on src/11_undefined_behaviour.md
> +- если код требует этих ключиков, то он, скорее всего, сломанный. Такое лучше написать как-то иначе.
убрал это предложение :)

2023-06-27 11:59 UTC, murysinm commented on src/12_validation.md
> +`+` **хорошо взаимодействует с отладчиками** - отладчики умеют показывать место, где упала программа. Например, linux умеет создать дамп своей памяти перед `std::abort`, и в отладчике можно посмотрет
fixed

2023-06-27 11:59 UTC, murysinm commented on src/08_exceptions.md
> +	**Unwinder** - раскручиватель стека. (мы у него можем спросить: вот если я сейчас сделаю `return`, то где я окажусь?). Когда летит исключение, надо понимать, откуда вызвана функция. Поэтому использу
fixed

2023-06-27 12:00 UTC, murysinm commented on src/07_inheritance.md
> +А почему `base b = d;` - не ошибка компиляции?
вроде везде поправил

2023-06-27 12:00 UTC, murysinm commented on src/04_syntax_types.md
> + - у `enum` не прописано, какой внутри тип внутри (underlying type). Причём, не прописано именно в стандарте. То есть, это может отличаться от компилятора к компилятору.
вроде везде поправил

2023-06-27 12:00 UTC, murysinm commented on src/04_syntax_types.md
> + - у `enum` не прописано, какой внутри тип внутри (underlying type). Причём, не прописано именно в стандарте. То есть, это может отличаться от компилятора к компилятору.
вроде везде поправил

2023-06-27 13:23 UTC, murysinm commented on src/04_syntax_types.md
> + - у `enum` не прописано, какой внутри тип внутри (underlying type). Причём, не прописано именно в стандарте. То есть, это может отличаться от компилятора к компилятору.
поправил

2023-06-27 20:45 UTC, murysinm commented on src/04_syntax_types.md
> +Есть еще обычный `enum`, без слова `class`. Это тип-перечисление, который пришел из Си. Но им лучше не пользоваться, потому что:
вроде заменил везде

2023-06-27 20:47 UTC, murysinm commented on src/04_syntax_types.md
> +А еще есть *функция `alignof`*.	Она возвращает *выравнивание* структуры. *Выравнивание* структуры - это число, на которое должен делиться тот адрес, по которому мы размещаем структуру. Использование:
добавил

2023-06-27 20:48 UTC, murysinm commented on src/07_inheritance.md
> +Так что тут у нас просто скопировались те мемберы, которые можно было скопировать, а мемберы `derived`'а потерялись.
переформулировал

2023-06-27 21:08 UTC, murysinm commented on src/08_exceptions.md
> +	**Unwinder** - раскручиватель стека. (мы у него можем спросить: вот если я сейчас сделаю `return`, то где я окажусь?). Когда летит исключение, надо понимать, откуда вызвана функция. Поэтому использу
вообще переписал это место, вынес мысли про раскручивание стека из перечисления.

2023-06-27 22:25 UTC, murysinm commented on src/07_inheritance.md
> +Кстати, у `derived`'а удалять эти функции уже не обязательно, они не сгенерятся, если у `base`'а удалены.
дописал и переформулировал

2023-06-28 17:43 UTC, dedlocc requested changes

2023-06-28 17:43 UTC, dedlocc commented on src/04_syntax_types.md
> +Кстати, `sizeof` и `alignof` можно применять не только к типам, но и к значениям.
А написать, что они в этом случае делают?

2023-06-28 17:43 UTC, dedlocc commented on src/04_syntax_types.md
> +По умолчанию внутри `enum class` лежит `int`. Тот тип, который лежит внутри, называется *underlying type*.
Думаю, стоит упомянуть, что его можно задать явно (как это сделано в примере выше)

2023-06-28 17:43 UTC, dedlocc commented on src/08_exceptions.md
> +Когда летит исключение, надо понимать, откуда вызвана функция. То есть, нужно раскручивать стэк вызова функций. И на самом деле основное время программа проводит, раскручивая стэк. А сам обработчик и
Уже писал про "то есть" и запятую)

2023-06-28 19:04 UTC, murysinm commented on src/04_syntax_types.md
> +Кстати, `sizeof` и `alignof` можно применять не только к типам, но и к значениям.
добавил

2023-06-28 19:05 UTC, murysinm commented on src/04_syntax_types.md
> +По умолчанию внутри `enum class` лежит `int`. Тот тип, который лежит внутри, называется *underlying type*.
кажется, это как раз следовало из примера выше.
но сейчас я чуть поменял предложение перед примером. наверное, теперь хорошо.

2023-06-28 19:09 UTC, murysinm commented on src/08_exceptions.md
> +Когда летит исключение, надо понимать, откуда вызвана функция. То есть, нужно раскручивать стэк вызова функций. И на самом деле основное время программа проводит, раскручивая стэк. А сам обработчик и
fixed:)

2023-06-29 07:41 UTC, dedlocc approved these changes

2023-06-29 07:42 UTC, merged