stack guard + wide/narrow contracts
CPP-KT/cpp-notes pull request #37
Opened 2023-09-27 09:20 UTC by gordeve

Добавил абзацы про stack guard и широкие/узкие контракты

2023-09-27 10:19 UTC, dedlocc requested changes

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
SIGSEGF -> SIGSEGV

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
Что, если

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +### Stack guard
"guard" в словосочетании "stack guard page" относится к "page", а не к "stack". Слово "stack" здесь как раз опциональное.

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +У нас стек строго определённого размера, и как проверять что произошёл stack overflow? Мы можем случайно наехать на чужую память, а это нехорошо.
чужую это чью? чем нехорошо? что произойдёт?

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
нет, она не так называется (см. коммент выше)

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
> современные проблемы требуют современных решений

непонятно, почему это современная проблема, про современность решения из контекста тоже неясно

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
где увеличили? оно одинаково работает на всех системах?

2023-09-27 10:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
лучше подробнее написать о том, где она располагается

2023-09-27 10:19 UTC, dedlocc commented on src/12_validation.md
> +У любой функции контракт может быть широким (wide) или узким (narrow). Если поведение функции специфицировано для любых входных данных, то считается что у неё **широкий** контракт, если же поведение
считается, что

2023-09-27 10:19 UTC, dedlocc commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
давай для тире использовать `—` или `&mdash;`

2023-09-27 10:19 UTC, dedlocc commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
поправь пунктуацию, невозможно читать (и вообще, переформулировал бы тут половину более лаконичными выражениями)

2023-09-27 10:19 UTC, dedlocc commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
проверки того что -> проверки на то, что

2023-09-27 13:54 UTC, gordeve commented on src/12_validation.md
> +У любой функции контракт может быть широким (wide) или узким (narrow). Если поведение функции специфицировано для любых входных данных, то считается что у неё **широкий** контракт, если же поведение
Fixed

2023-09-27 13:56 UTC, gordeve commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
Fixed

2023-09-27 14:01 UTC, gordeve commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
Fixed

2023-09-27 14:43 UTC, gordeve commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
Fixed

2023-09-27 14:44 UTC, gordeve commented on src/02_os_cpu.md
> +### Stack guard
Fixed

2023-09-27 14:45 UTC, gordeve commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
Fixed

2023-09-27 14:46 UTC, gordeve commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
Fixed

2023-09-27 14:49 UTC, gordeve commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
Fixed

2023-09-27 14:50 UTC, gordeve commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
Fixed :)

2023-09-27 16:50 UTC, gordeve commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
Fixed

2023-09-27 16:55 UTC, gordeve commented on src/02_os_cpu.md
> +У нас стек строго определённого размера, и как проверять что произошёл stack overflow? Мы можем случайно наехать на чужую память, а это нехорошо.
Fixed

2023-09-27 16:55 UTC, gordeve commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
Fixed

2023-09-27 23:19 UTC, dedlocc requested changes

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +### Stack guard
не везде поправил

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
я не понимаю, что такое "слева от стека"

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +У нас стек строго определённого размера, и как проверять что произошёл stack overflow? Мы можем случайно наехать на чужую память, а это нехорошо.
"внешние данные" всё ещё очень расплывчато

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
[note] решение так-то и правда современное, если считать таковым 2017 год: https://github.com/torvalds/linux/commit/1be7107fbe18eed3e319a6c3e83c78254b693acb

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +В Linux проблему решили следующим образом - размер stack guard просто увеличили до 1 мегабайта.
писал уже про то, как писать тире

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +В Windows решили воспользоваться тем, что страницы выделяются не сразу, а только после обращения к ним. Таким образом, требуется чтобы page fault'ы стека происходили подряд, иначе мы словим access vi
"Таким образом" здесь неуместно, ты же вводишь новую информацию, а не пытаешься сделать какой-то вывод или обобщить сказанное ранее

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +В Windows решили воспользоваться тем, что страницы выделяются не сразу, а только после обращения к ним. Таким образом, требуется чтобы page fault'ы стека происходили подряд, иначе мы словим access vi
требуется, чтобы

2023-09-27 23:19 UTC, dedlocc commented on src/02_os_cpu.md
> +В Windows решили воспользоваться тем, что страницы выделяются не сразу, а только после обращения к ним. Таким образом, требуется чтобы page fault'ы стека происходили подряд, иначе мы словим access vi
перепрыгнуть guard page невозможно, потому что сначала мы должны будем обратиться в guard page? что? это же не перепрыгивание тогда

2023-09-27 23:19 UTC, dedlocc commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции класса `std::vector` &mdash; `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают `ind`-ый элемент вектора. При этом, у квадратных скобок будет узкий
`ind` не очень распространённое сокращение для индекса, лучше было бы любое из: `pos` (как на cppreference), `n` (как в стандарте языка), `idx` или хотя бы `i`

2023-09-27 23:19 UTC, dedlocc commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции класса `std::vector` &mdash; `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают `ind`-ый элемент вектора. При этом, у квадратных скобок будет узкий
после "Если же" два пробела

2023-09-27 23:19 UTC, dedlocc commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
отвечай чуть подробнее, если из оригинального замечания непонятно, что именно изменилось (в данном случае ты вообще удалил это выражение)

2023-09-28 12:52 UTC, gordeve commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции класса `std::vector` &mdash; `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают `ind`-ый элемент вектора. При этом, у квадратных скобок будет узкий
Fixed

2023-09-28 12:53 UTC, gordeve commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции класса `std::vector` &mdash; `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают `ind`-ый элемент вектора. При этом, у квадратных скобок будет узкий
Fixed

2023-09-28 13:16 UTC, gordeve commented on src/12_validation.md
> +Рассмотрим, к примеру, две функции `std::vector` - `operator[](size_t ind)` и `at(size_t ind)`. Обе функции возвращают элемент вектора с указанным индексом, но при этом у квадратных скобок будет узки
Fixed, переписал полностью выражение

2023-09-28 13:18 UTC, gordeve commented on src/02_os_cpu.md
> +### Stack guard
Fixed

2023-09-28 13:22 UTC, gordeve commented on src/02_os_cpu.md
> +Вот только не совсем. Что если мы *перепрыгнули* за stack guard (т.е. увеличили стек на несколько страниц за раз)? Тогда всё снова плохо. Ну, современные проблемы требуют современных решений, поэтому
Убрал чтобы не путать людей, комментарий был не по теме

2023-09-30 22:37 UTC, gordeve commented on src/02_os_cpu.md
> +У нас стек строго определённого размера, и как проверять что произошёл stack overflow? Мы можем случайно наехать на чужую память, а это нехорошо.
Fixed

2023-09-30 22:39 UTC, gordeve commented on src/02_os_cpu.md
> +Для предотвращения этого стеку зарезервировали специальную страницу, называемую stack guard. Теперь, если мы перешли за границу стека, то мы обращаемся к стек гарду, он недоступен и мы получаем SIGSE
Fixed, исправил на "снизу стека"

2023-09-30 22:42 UTC, gordeve commented on src/02_os_cpu.md
> +В Linux проблему решили следующим образом - размер stack guard просто увеличили до 1 мегабайта.
Fixed

2023-09-30 22:42 UTC, gordeve commented on src/02_os_cpu.md
> +В Windows решили воспользоваться тем, что страницы выделяются не сразу, а только после обращения к ним. Таким образом, требуется чтобы page fault'ы стека происходили подряд, иначе мы словим access vi
Fixed, убрал

2023-09-30 22:42 UTC, gordeve commented on src/02_os_cpu.md
> +В Windows решили воспользоваться тем, что страницы выделяются не сразу, а только после обращения к ним. Таким образом, требуется чтобы page fault'ы стека происходили подряд, иначе мы словим access vi
Fixed

2023-09-30 22:43 UTC, gordeve commented on src/02_os_cpu.md
> +В Windows решили воспользоваться тем, что страницы выделяются не сразу, а только после обращения к ним. Таким образом, требуется чтобы page fault'ы стека происходили подряд, иначе мы словим access vi
Fixed

2023-10-04 10:39 UTC, dedlocc approved these changes

2023-10-04 10:40 UTC, merged