Your commit message
CPP-KT/cpp-notes pull request #39
Opened 2023-10-22 11:01 UTC by petrushkanya

2023-10-24 19:48 UTC, dedlocc requested changes

2023-10-24 19:48 UTC, dedlocc commented on src/06_classes.md
> +
по этому описанию про pimpl ничего не понять, нужны примеры и разбор типичных проблем (например, почему не получится задефолтить деструктор в заголовочном файле)

2023-10-24 19:48 UTC, dedlocc commented on src/12_validation.md
> +Еще есть static_assert, который используется для выполнения проверок во время компиляции. Если статическое утверждение не выполняется, то программа просто не компилируется.
тоже примеров не хватает
ещё мне не нравится здесь слово "утверждение"

2023-10-25 08:45 UTC, petrushkanya commented on src/06_classes.md
> +
добавила два примера

2023-10-25 08:46 UTC, petrushkanya commented on src/12_validation.md
> +Еще есть static_assert, который используется для выполнения проверок во время компиляции. Если статическое утверждение не выполняется, то программа просто не компилируется.
добавила пример

2023-10-26 00:09 UTC, dedlocc requested changes
по всем изменениям много trailing пробелов в разных строчках, зачем они? во многих IDE есть плагины для подсветки или автоматического удаления подобного

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +Еще есть static_assert, который используется для выполнения проверок во время компиляции. Если static_assert не выполняется, то программа просто не компилируется.
static_assert -> `static_assert`

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +### Static_assert
может просто "Static asserts"? а то странное тут нижнее подчёркивание

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +	class noEmptyContainer {
`noEmptyContainer` -> `NonEmptyContainer`

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +```
почему табы? в этом же файле в других сниппетах табуляция пробелами

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +```
можно ещё добавить сюда же пример с проверкой `sizeof` этой структуры, чтоб показать больше применений, чем проверка темплейтных параметров

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +	}
забыта `;`

2023-10-26 00:09 UTC, dedlocc commented on src/12_validation.md
> +```
один из примеров можно дополнить вторым аргументом &mdash; сообщением ошибки, которая будет выведена компилятором при невыполнении условия в `static_assert'е

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
> (его в том числе)

можно было бы подумать, будто речь идёт о компиляции самого заголовочного файла

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
все -> всё

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
> Одним из решений этой проблемы стало использование идиомы PImpl

где стало? давай более нейтрально введём эту идиому

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
ее -> её

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +	std::unique_ptr<Impl> pimpl;
tab

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +// impl.cpp
`container.cpp`

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +struct Container::Impl {
а объявлен был как `class`.. так технически разрешено, но не надо

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +    ~Impl();
зачем объявление деструктора? и определения нет нигде

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +    Impl(size_t size) : size(size) {};
лишняя `;`

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Теперь все изменения будут вноситься в impl.cpp и пользователю не надо перекомпилировать файлы.
```suggestion
Теперь все изменения будут вноситься в `container.cpp`, и пользователю не надо перекомпилировать другие единицы трансляции &mdash; только перелинковаться.
```

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Рассмотрим еще такой пример:
еще -> ещё

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +private :
пробел

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Рассмотрим еще такой пример:
я б не сказал, что "ещё", это пряма регрессия предыдущего примера

может подойти со стороны "а зачем мы вынесли деструктор, что если так не делать"?

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +struct mytype {
в предыдущем примере между названием файла и кодом была пустая строка, здесь нет, давай как-то единообразно

\+ нейминг другой стал

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +У нас не будет компилироваться main. Ошибка в том, что unique_ptr пытается delet'ить incomplete тип. А значит ошибка в implicit member в a.h, а это связано с деструктором ~mytype(). Если мы объявим д
не забывай backticks

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +    struct impl;
зачем он публичный?

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Зачем мы перетянули сюда еще и конструктор ? Это связано с тем, как генерится дефолтный конструтор. Нам кажется, что он пустой, но на самом деле такой конструтор вызывает конструктор member'ов.
- еще -> ещё
- лишний пробел

2023-10-26 00:09 UTC, dedlocc commented on src/06_classes.md
> +Зачем мы перетянули сюда еще и конструктор ? Это связано с тем, как генерится дефолтный конструтор. Нам кажется, что он пустой, но на самом деле такой конструтор вызывает конструктор member'ов.
а в чём аргумент? ну вызывает и вызывает

и ты же `pimpl` тут нигде не инициализируешь

не понял в общем, зачем эта часть вообще

2023-10-26 05:23 UTC, petrushkanya commented on src/12_validation.md
> +```
Все добавила

2023-10-26 05:27 UTC, petrushkanya commented on src/12_validation.md
> +Еще есть static_assert, который используется для выполнения проверок во время компиляции. Если static_assert не выполняется, то программа просто не компилируется.
исправила

2023-10-26 05:28 UTC, petrushkanya commented on src/12_validation.md
> +### Static_assert
исправила

2023-10-26 05:28 UTC, petrushkanya commented on src/12_validation.md
> +	}
исправила

2023-10-26 05:37 UTC, petrushkanya commented on src/06_classes.md
> +// impl.cpp
исправила

2023-10-26 05:37 UTC, petrushkanya commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
исправила

2023-10-26 05:38 UTC, petrushkanya commented on src/06_classes.md
> +struct Container::Impl {
исправила на класс

2023-10-26 05:39 UTC, petrushkanya commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
Вроде стало лучше

2023-10-26 05:40 UTC, petrushkanya commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
ага

2023-10-26 05:42 UTC, petrushkanya commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него (его в том числе). А это будет заним
Исправила

2023-10-26 05:43 UTC, petrushkanya commented on src/06_classes.md
> +    ~Impl();
Убрала

2023-10-26 05:43 UTC, petrushkanya commented on src/06_classes.md
> +    Impl(size_t size) : size(size) {};
Убрала

2023-10-26 05:48 UTC, petrushkanya commented on src/06_classes.md
> +struct Container::Impl {
ой, на структуру

2023-10-26 05:48 UTC, petrushkanya commented on src/06_classes.md
> +Теперь все изменения будут вноситься в impl.cpp и пользователю не надо перекомпилировать файлы.
Спасибо, добавила

2023-10-26 05:49 UTC, petrushkanya commented on src/06_classes.md
> +Рассмотрим еще такой пример:
Исправила

2023-10-26 05:50 UTC, petrushkanya commented on src/06_classes.md
> +private :
убрала

2023-10-26 09:52 UTC, petrushkanya commented on src/06_classes.md
> +Зачем мы перетянули сюда еще и конструктор ? Это связано с тем, как генерится дефолтный конструтор. Нам кажется, что он пустой, но на самом деле такой конструтор вызывает конструктор member'ов.
я убрала эту  часть

2023-10-26 09:52 UTC, petrushkanya commented on src/06_classes.md
> +    struct impl;
сделала приватным

2023-10-26 09:55 UTC, petrushkanya commented on src/06_classes.md
> +struct mytype {
вроде поправила

2023-10-26 09:57 UTC, petrushkanya commented on src/06_classes.md
> +Рассмотрим еще такой пример:
Исправила

2023-10-26 10:01 UTC, petrushkanya commented on src/06_classes.md
> +У нас не будет компилироваться main. Ошибка в том, что unique_ptr пытается delet'ить incomplete тип. А значит ошибка в implicit member в a.h, а это связано с деструктором ~mytype(). Если мы объявим д
Поставила

2023-10-26 10:02 UTC, petrushkanya commented on src/06_classes.md
> +	std::unique_ptr<Impl> pimpl;
убрала

2023-10-26 10:03 UTC, petrushkanya commented on src/12_validation.md
> +```
убрала

2023-10-26 21:47 UTC, dedlocc requested changes

2023-10-26 21:47 UTC, dedlocc commented on src/12_validation.md
> +### `Static asserts`
но зачем тут-то backticks :(

2023-10-26 21:47 UTC, dedlocc commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него. А это будет занимать много времени,
может так?

```suggestion
Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него. А это будет занимать много времени, ведь даже при небольших изменениях приходится ждать, пока всё перекомпилируется.

На помощь приходит идиома PImpl, которая позволяет отделить интерфейс класса от его реализации. Её идея в том, чтобы перенести приватные поля в отдельный класс и обращаться к ним через указатель. 
```

2023-10-26 21:47 UTC, dedlocc commented on src/06_classes.md
> +	struct Impl;
и опять таб

2023-10-26 21:47 UTC, dedlocc commented on src/06_classes.md
> +Мы вынесли деструктор. А что будет, если так не сделать ?
лишний пробел

2023-10-26 21:47 UTC, dedlocc commented on src/06_classes.md
> +struct Mytype {
`MyType` тогда уж?

2023-10-26 21:47 UTC, dedlocc commented on src/12_validation.md
> +    static_assert(sizeof(a2) == sizeof(long long) * 10);// ок
не хватает пробела

2023-10-26 21:47 UTC, dedlocc commented on src/06_classes.md
> +struct Mytype {
а в чём смысл рассматривать какой-то другой пример, а не тот же? главное доступно объяснить, зачем нужен вынос деструткора

2023-10-26 21:47 UTC, dedlocc commented on src/06_classes.md
> +У нас не будет компилироваться `main`. Ошибка в том, что `unique_ptr` пытается delet'ить incomplete тип. А значит ошибка в implicit member в `a.h`, а это связано с деструктором `~mytype()`. Если мы о
- объявим -> определим
- все -> всё
- давай второе предложение более прямо, что деструктор `unique_ptr` пытается вызывать деструктор incomplete типа, а не непонятное "проблема в implicit member в a.h"

2023-10-26 21:50 UTC, petrushkanya commented on src/12_validation.md
> +### `Static asserts`
убрала

2023-10-26 21:51 UTC, petrushkanya commented on src/06_classes.md
> +Представим, что у нас есть большой проект/библиотека и мы хотим как-то изменить заголовочный файл. Тогда надо перекомпилировать все файлы, которые зависят от него. А это будет занимать много времени,
Поменяла

2023-10-26 21:53 UTC, petrushkanya commented on src/06_classes.md
> +Мы вынесли деструктор. А что будет, если так не сделать ?
убрала

2023-10-26 21:54 UTC, petrushkanya commented on src/06_classes.md
> +struct Mytype {
ага

2023-10-27 13:17 UTC, petrushkanya commented on src/06_classes.md
> +struct Mytype {
Я убрала mytype вообще и просто написала ответ про деструктор

2023-10-27 13:22 UTC, petrushkanya commented on src/06_classes.md
> +У нас не будет компилироваться `main`. Ошибка в том, что `unique_ptr` пытается delet'ить incomplete тип. А значит ошибка в implicit member в `a.h`, а это связано с деструктором `~mytype()`. Если мы о
Убрала последние два предложения, написала, как вы сказали

2023-10-27 13:23 UTC, petrushkanya commented on src/12_validation.md
> +    static_assert(sizeof(a2) == sizeof(long long) * 10);// ок
добавила

2023-10-27 13:25 UTC, petrushkanya commented on src/06_classes.md
> +struct Mytype {
Я его убрала, оставила только контейнер

2023-10-28 13:42 UTC, dedlocc approved these changes

2023-10-28 13:43 UTC, merged