fixes and additions
CPP-KT/cpp-notes pull request #40
Opened 2023-10-22 16:09 UTC by annnaarkh

2023-10-24 20:12 UTC, dedlocc requested changes

2023-10-24 20:12 UTC, dedlocc commented on src/09_allocations_optimizations.md
> +			sizeof(buffer) + capacity * sizeof(char)
почему убрала?

2023-10-24 20:12 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +Такая функция приведётся к `return false`. Но человек смотрит на то, что в процессоре это совершенно чётко работает, и не понимает, почему в C++ не работает. А дело в том, что **опасно при изучении т
наверное, "приведётся" -> "сведётся"?

2023-10-24 20:12 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +Другое неправильное понимание UB — вот такая попытка проверить переполнение типа:
здесь переполнение лишь средство, а не цель функции, так что попытка не "проверить переполнение"

2023-10-24 20:12 UTC, dedlocc commented on src/11_undefined_behaviour.md
> +Такая функция приведётся к `return false`. Но человек смотрит на то, что в процессоре это совершенно чётко работает, и не понимает, почему в C++ не работает. А дело в том, что **опасно при изучении т
опять же, не идёт речи о проверке переполнения, тут тем более

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
здесь есть неточность: forward итераторы, в отличие от чисто input/output, поддерживают постинкремент

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
> то есть меняется состояние также всех копий итератора

для `std::istream_iterator` и `std::ostream_iterator` это правда, но в общем случае нет

single pass значит, что при инкременте итератора все его копии инвалидируются (если писать об этом, надо не забыть ввести понятие инвалидации итераторов, желательно с упоминанием примеров)

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> +Самая мощная категория итераторов - *random access*. Ко всем предыдущим поддерживающимся в итераторах операциям добавляются:
а contiguous?

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> +Самая мощная категория итераторов - *random access*. Ко всем предыдущим поддерживающимся в итераторах операциям добавляются:
для тире используй `&mdash;`

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> +Примеры random access итераторов: std::vector, std::array, pointer. Random access итераторы требуются для функций, где необходимо уметь прыгать через n элементов: сортировки, k-я порядковая статистик
`std::vector` это не итератор, указатель это действительно итератор &mdash; тут явно какое-то разногласие (а ещё backticks не используются)

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> +![reverse iterators vision](./images/reverse_iterators_vision.png)
имхо странно показывать картинку, как можно альтернативно смотреть на reverse iterators, до того, как собственно объяснить, что это такое и как они устроены

вот если бы тут аккуратно попереставлять абзацы местами...

2023-10-24 20:12 UTC, dedlocc commented on src/15_stl.md
> -
что тут произошло?

2023-10-25 16:10 UTC, annnaarkh commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
fixed

2023-10-25 16:10 UTC, annnaarkh commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
fixed, изменила

2023-10-25 16:10 UTC, annnaarkh commented on src/15_stl.md
> +Самая мощная категория итераторов - *random access*. Ко всем предыдущим поддерживающимся в итераторах операциям добавляются:
написала о них

2023-10-25 16:10 UTC, annnaarkh commented on src/15_stl.md
> +Самая мощная категория итераторов - *random access*. Ко всем предыдущим поддерживающимся в итераторах операциям добавляются:
fixed

2023-10-25 16:10 UTC, annnaarkh commented on src/15_stl.md
> +Примеры random access итераторов: std::vector, std::array, pointer. Random access итераторы требуются для функций, где необходимо уметь прыгать через n элементов: сортировки, k-я порядковая статистик
fixed

2023-10-25 16:11 UTC, annnaarkh commented on src/15_stl.md
> +![reverse iterators vision](./images/reverse_iterators_vision.png)
попереставляла, думаю, теперь порядок оптимальный для объяснения

2023-10-25 16:11 UTC, annnaarkh commented on src/15_stl.md
> -
видимо, я случайно удалила пустую строчку в конце файла; вернула

2023-10-25 16:12 UTC, annnaarkh commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
я решила в целом переписать информацию про категории итераторов; могу вернуть, но мне кажется, что так более структурированно выглядит

2023-10-25 16:20 UTC, annnaarkh commented on src/09_allocations_optimizations.md
> +			sizeof(buffer) + capacity * sizeof(char)
нам не нужен этот +1, ведь мы должны выделить память для структурки + количества элементов типа char, равного capacity

2023-10-25 16:45 UTC, annnaarkh commented on src/11_undefined_behaviour.md
> +Такая функция приведётся к `return false`. Но человек смотрит на то, что в процессоре это совершенно чётко работает, и не понимает, почему в C++ не работает. А дело в том, что **опасно при изучении т
fixed

2023-10-25 16:46 UTC, annnaarkh commented on src/11_undefined_behaviour.md
> +Другое неправильное понимание UB — вот такая попытка проверить переполнение типа:
fixed

2023-10-25 16:46 UTC, annnaarkh commented on src/11_undefined_behaviour.md
> +Такая функция приведётся к `return false`. Но человек смотрит на то, что в процессоре это совершенно чётко работает, и не понимает, почему в C++ не работает. А дело в том, что **опасно при изучении т
fixed

2023-10-26 00:34 UTC, dedlocc requested changes

2023-10-26 00:34 UTC, dedlocc commented on src/09_allocations_optimizations.md
> +			sizeof(buffer) + capacity * sizeof(char)
для строк часто `capacity` хранится без учёта нуль-терминатора

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
изложение итераторов нехорошо начинать с input/output &mdash; их концепция сложнее, чем тот же forward iterator

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +При инкременте **input** или **output** итератора все его копии инвалидируются.
"В общем случае", иначе можно подумать, что это относится и к двум только что упомянутым примерам

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
в каком-то смысле, они указывают всё туда же, обратное потребовало бы проходиться по ним (как в debug-set), что не всегда вообще возможно, а если возможно, то неэффективно

инвалидация лишь ограничивает кол-во операций, которые с итератором можно делать, до минимума (разрушить, присвоить другой итератор)

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
перед "в случае" не хватает тире

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
вижу закрывающую скобку без открывающей

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +**Forward** итераторы позволяют пройтись по диапазону несколько раз. **Forward** итератор поддерживает все те же операции, что и **input** итератор, и, если он изменяемый, то он также поддерживает оп
"изменяемый" странное слово тут, присвоить другой итератор-то можно

в целом, достаточно упомянуть, что является output итератором опционально

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +**Forward** итераторы позволяют пройтись по диапазону несколько раз. **Forward** итератор поддерживает все те же операции, что и **input** итератор, и, если он изменяемый, то он также поддерживает оп
почему первые 2 предложения с заглавной буквы, а 3-е &mdash; со строчной?

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +**Random access** итераторы поддерживают такие контейнеры, как `std::vector`, `std::array`. Указатели также поддерживают интерфейс **random access** итераторов. **Random access** итераторы требуются
> Указатели также поддерживают интерфейс **random access** итераторов

указатели **являются** простейшим примером итераторов (contiguous, если быть точнее, ну и все остальные категории соответственно тоже)

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +**Random access** итераторы поддерживают такие контейнеры, как `std::vector`, `std::array`. Указатели также поддерживают интерфейс **random access** итераторов. **Random access** итераторы требуются
почему перечисление примеров в ``?

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +В `C++20` появились **contiguous** итераторы. Они поддерживают все операции, поддерживаемые **random access** итераторами, и при этом гарантируют, что элементы хранятся в памяти последовательно.
не уверен, что версию стандарта стоит заключать в backticks. или так ещё где-то в cpp-notes делается?

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +**Random access** — самая мощная категория итераторов. Ко всем предыдущим поддерживающимся в итераторах операциям добавляются:
для тире просил использовать `&mdash;`

2023-10-26 00:34 UTC, dedlocc commented on src/15_stl.md
> +![reverse iterators vision](./images/reverse_iterators_vision.png)
не согласен, что новая картинка может идти раньше старой: как можно смотреть с "другой" стороны, не посмотрев сначала с исходной?

давай сначала полностью расскажем всё про reverse итераторы, чтобы пример был понятен, а потом уже посмотрим с другой стороны, подведя итог этого пункта

2023-10-26 03:03 UTC, annnaarkh commented on src/09_allocations_optimizations.md
> +			sizeof(buffer) + capacity * sizeof(char)
fixed, вернула +1 и дописала ваше пояснение

2023-10-26 09:47 UTC, annnaarkh commented on src/15_stl.md
> +**Forward** итераторы позволяют пройтись по диапазону несколько раз. **Forward** итератор поддерживает все те же операции, что и **input** итератор, и, если он изменяемый, то он также поддерживает оп
Я решила убрать это, раз про forward итераторы рассказ теперь выше, чем про output и input

2023-10-26 09:48 UTC, annnaarkh commented on src/15_stl.md
> +но позволяют пройти по диапазону только один раз, то есть меняется состояние также всех копий итератора (например, поток ввода/вывода).
Теперь сначала рассказываю про forward

2023-10-26 09:50 UTC, annnaarkh commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
fixed, переписала на такое определение

2023-10-26 09:59 UTC, annnaarkh commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
Думаю, в данном случае всё-таки запятой не хватает; это уточнение, и если его тире обособлять, то тире должно быть с двух сторон
Мне кажется, тут было бы тире, если бы не было последней части (*инвалидируются все итераторы*), но я могу ошибаться

2023-10-26 09:59 UTC, annnaarkh commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
Пока что добавила запятую

2023-10-26 09:59 UTC, annnaarkh commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
(что-то такое) https://orfogrammka.ru/%D1%82%D0%BE%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D0%BD%D1%82/%D0%BF%D0%B0%D1%80%D0%BD%D1%8B%D0%B5-%D0%B7%D0%B0%D0%BF%D1%8F%D1%82%D1%8B%D0%B5-%D0%B8-%D1%82%D0%B8%D1%80%D0%B5-%D0%BF%D1%80%D0%B8-%D1%83%D1%82%D0%BE%D1%87%D0%BD%D0%B5%D0%BD%D0%B8%D0%B8/#:~:text=%D0%A3%D1%82%D0%BE%D1%87%D0%BD%D1%8F%D1%8E%D1%89%D0%B8%D0%B5%20%D1%87%D0%BB%D0%B5%D0%BD%D1%8B%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B2%D1%8B%D0%B4%D0%B5%D0%BB%D1%8F%D1%8E%D1%82%D1%81%D1%8F%20%D0%B7%D0%B0%D0%BF%D1%8F%D1%82%D1%8B%D0%BC%D0%B8,%D0%B3%D0%BE%D1%80%D0%B0%D1%85%20%2C%20%D0%BF%D0%BE%D0%B2%D0%B0%D0%BB%D0%B8%D0%BB%20%D1%81%D0%BD%D0%B5%D0%B3%20(%D0%A2.

2023-10-26 09:59 UTC, annnaarkh commented on src/15_stl.md
> +При **инвалидации** итераторы перестают указывать туда, куда должны были указывать; к примеру, в `std::vector`'е после удаления некого элемента происходит инвалидация итераторов, указывающих на него
fixed

2023-10-26 10:00 UTC, annnaarkh commented on src/15_stl.md
> +**Forward** итераторы позволяют пройтись по диапазону несколько раз. **Forward** итератор поддерживает все те же операции, что и **input** итератор, и, если он изменяемый, то он также поддерживает оп
Сейчас этого предложения нет, так что fixed

2023-10-26 10:01 UTC, annnaarkh commented on src/15_stl.md
> +**Random access** итераторы поддерживают такие контейнеры, как `std::vector`, `std::array`. Указатели также поддерживают интерфейс **random access** итераторов. **Random access** итераторы требуются
fixed

2023-10-26 10:03 UTC, annnaarkh commented on src/15_stl.md
> +**Random access** итераторы поддерживают такие контейнеры, как `std::vector`, `std::array`. Указатели также поддерживают интерфейс **random access** итераторов. **Random access** итераторы требуются
Просто подумала, что примеры контейнеров в ``, так что можно для одинакового вида и другие примеры так отформатировать (хотя это и не код)
Fixed, сделала **

2023-10-26 10:03 UTC, annnaarkh commented on src/15_stl.md
> +В `C++20` появились **contiguous** итераторы. Они поддерживают все операции, поддерживаемые **random access** итераторами, и при этом гарантируют, что элементы хранятся в памяти последовательно.
fixed

2023-10-26 10:34 UTC, annnaarkh commented on src/15_stl.md
> +**Random access** — самая мощная категория итераторов. Ко всем предыдущим поддерживающимся в итераторах операциям добавляются:
fixed

2023-10-26 10:35 UTC, annnaarkh commented on src/15_stl.md
> +![reverse iterators vision](./images/reverse_iterators_vision.png)
fixed

2023-10-26 10:46 UTC, annnaarkh commented on src/15_stl.md
> +При инкременте **input** или **output** итератора все его копии инвалидируются.
fixed

2023-10-26 21:57 UTC, dedlocc requested changes

2023-10-26 21:57 UTC, dedlocc commented on src/15_stl.md
> +- `it -> x`
с пробелами и я не сразу понял, что эта запись значит, уж думал каст какой-то
наверное, лучше без них

2023-10-26 21:57 UTC, dedlocc commented on src/15_stl.md
> +**Forward** итераторы (в отличие от рассмотреных далее **input** и **output** итераторов) позволяют пройтись по диапазону несколько раз. **Forward** итератор поддерживает такие операции:
не надо это упоминать тут и нагружать информацией, давай просто дальше чётко отметим разницу

2023-10-26 21:57 UTC, dedlocc commented on src/15_stl.md
> +Для любых **input** и **output** итераторов при инкременте все их копии инвалидируются.
ну это же всё ещё не верно, опять же для итераторов выше

и ты это вносишь как будто это отдельный факт, а не объяснение "позволяют пройти только один раз"

2023-10-26 21:57 UTC, dedlocc commented on src/15_stl.md
> +**Random access** итераторы поддерживают такие контейнеры, как `std::vector`, `std::array`. Указатели также являются **random access** итераторами (на самом деле даже **contigious**, описанными ниже)
```suggestion
**Random access** итераторы свойственны таким контейнерам, как `std::vector`, `std::array`. Указатели также являются **random access** итераторами (на самом деле даже **contigious**, описанными ниже). **Random access** итераторы требуются для функций, где необходимо уметь прыгать через n элементов: *сортировки, k-я порядковая статистика, бинарный поиск* и т.д.
```

2023-10-26 21:57 UTC, dedlocc commented on src/15_stl.md
>  Тогда итератору `rbegin()` соответствует `end()`, а `rend()` это `begin()`. Реверс-итераторы позволяют пройти контейнер в обратную сторону.
попробуй это перечитать, и скажи мне, что логика повествования понятна (я считаю, что совсем нет)

2023-10-26 22:33 UTC, annnaarkh commented on src/15_stl.md
> +- `it -> x`
fixed

2023-10-26 22:40 UTC, annnaarkh commented on src/15_stl.md
> +**Forward** итераторы (в отличие от рассмотреных далее **input** и **output** итераторов) позволяют пройтись по диапазону несколько раз. **Forward** итератор поддерживает такие операции:
fixed

2023-10-26 22:42 UTC, annnaarkh commented on src/15_stl.md
> +Для любых **input** и **output** итераторов при инкременте все их копии инвалидируются.
fixed, перенесла к "позволяют пройти один раз"

2023-10-26 22:57 UTC, annnaarkh commented on src/15_stl.md
>  Тогда итератору `rbegin()` соответствует `end()`, а `rend()` это `begin()`. Реверс-итераторы позволяют пройти контейнер в обратную сторону.
теперь вроде понятна

2023-10-28 13:22 UTC, dedlocc approved these changes

2023-10-28 13:25 UTC, merged