grammar, punctuation, table formatting
CPP-KT/cpp-notes pull request #41
Opened 2023-10-28 15:19 UTC by easylaneof

2023-10-29 11:45 UTC, dedlocc requested changes

2023-10-29 11:45 UTC, dedlocc commented on src/10_libraries.md
> +Например, библиотека для работы с JSON хочет делать `fopen`. То есть нужно подружить библиотеки друг с другом. Самый простой вариант — когда мы делаем `call`, в файл мы кладём нулевой адрес, а в секц
почему здесь нужна запятая?

2023-10-29 11:45 UTC, dedlocc commented on src/12_validation.md
> +`valgrind` и sanitizer'ы — это не единственное, что вы можете. И, что более важно, они не всегда вам помогут.\
зачем? курсив ок

2023-10-29 11:45 UTC, dedlocc commented on src/22_lambdas_type_erasure.md
> +`any` можно реализовать аналогично реализации function, которая приведена выше. Но можно реализовать проще через динамический полиморфизм:
здесь в конце лишний пробел

2023-10-29 11:45 UTC, dedlocc commented on src/24_optional_variant_tuple_stringview.md
> +Это лучше тем, что если появится ещё один класс `derived4`, то нужно будет добавить функцию в `visitor`, не меняя интерфейс класса (особенно это важно, если его изменение недоступно).
и здесь

2023-10-29 11:45 UTC, dedlocc commented on src/26_multithreading.md
> +Также `memory_order_relaxed` можно использовать при записи в память до создания других потоков, потому что их создание так же гарантирует, что они увидят все записи, сделанные до этого.
также

2023-10-29 11:45 UTC, dedlocc commented on src/26_multithreading.md
> +Один из первых известных аллокаторов с понятным описанием это [Hoard](http://hoard.org/). Хоть он и устарел и на практике уже давно не применяется, концепции, описанные там, переняли разработчики дру
ещё один лишний пробел в конце

2023-10-29 11:45 UTC, dedlocc commented on src/28_concepts.md
> +С концептами это будет выглядеть так: ```template <requires is_iterator It> ```
и ещё (давай не буду больше писать, сам найдёшь)

2023-10-29 11:45 UTC, dedlocc commented on src/31_coroutines.md
> +Иногда после ожидания мы хотим получить какой-то результат как тут:
почему не нужна запятая?

2023-10-29 13:24 UTC, easylaneof commented on src/22_lambdas_type_erasure.md
> +`any` можно реализовать аналогично реализации function, которая приведена выше. Но можно реализовать проще через динамический полиморфизм:
fixed

2023-10-29 13:24 UTC, easylaneof commented on src/12_validation.md
> +`valgrind` и sanitizer'ы — это не единственное, что вы можете. И, что более важно, они не всегда вам помогут.\
fixed

2023-10-29 13:26 UTC, easylaneof commented on src/26_multithreading.md
> +Также `memory_order_relaxed` можно использовать при записи в память до создания других потоков, потому что их создание так же гарантирует, что они увидят все записи, сделанные до этого.
Да вроде бы нет пробела

2023-10-29 13:26 UTC, easylaneof commented on src/26_multithreading.md
> +Один из первых известных аллокаторов с понятным описанием это [Hoard](http://hoard.org/). Хоть он и устарел и на практике уже давно не применяется, концепции, описанные там, переняли разработчики дру
fixed

2023-10-29 13:27 UTC, easylaneof commented on src/28_concepts.md
> +С концептами это будет выглядеть так: ```template <requires is_iterator It> ```
fixed

2023-10-29 13:39 UTC, easylaneof commented on src/31_coroutines.md
> +Иногда после ожидания мы хотим получить какой-то результат как тут:
согласен, вернул

2023-10-29 13:40 UTC, easylaneof commented on src/10_libraries.md
> +Например, библиотека для работы с JSON хочет делать `fopen`. То есть нужно подружить библиотеки друг с другом. Самый простой вариант — когда мы делаем `call`, в файл мы кладём нулевой адрес, а в секц
согласен, убрал

2023-10-29 13:42 UTC, easylaneof commented
По пробелам в конце можно глобально прогнать форматтер, который их уберет. Их добавили не мои изменения, они были исходно

2023-10-29 15:08 UTC, easylaneof commented on src/24_optional_variant_tuple_stringview.md
> +Это лучше тем, что если появится ещё один класс `derived4`, то нужно будет добавить функцию в `visitor`, не меняя интерфейс класса (особенно это важно, если его изменение недоступно).
fixed

2023-10-29 16:48 UTC, dedlocc commented on src/26_multithreading.md
> +Также `memory_order_relaxed` можно использовать при записи в память до создания других потоков, потому что их создание так же гарантирует, что они увидят все записи, сделанные до этого.
так же -> "также"

2023-10-29 16:51 UTC, easylaneof commented on src/26_multithreading.md
> +Также `memory_order_relaxed` можно использовать при записи в память до создания других потоков, потому что их создание так же гарантирует, что они увидят все записи, сделанные до этого.
fixed

2023-10-30 11:39 UTC, dedlocc reviewed
Комментарии закрывает ревьюер, а не ты

2023-10-30 11:39 UTC, dedlocc approved these changes

2023-10-30 11:56 UTC, merged