Add more information about ranges.
CPP-KT/cpp-notes pull request #46
Opened 2024-03-30 01:31 UTC by brokenken

2024-03-30 09:34 UTC, dedlocc requested changes

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +если нужно сортировать некоторый подотрезок, она нам подходит.
не стоит разбивать предложения в случайных местах на строки

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +А функция, которая принимает вектор целиком более частный случай.
не хватает запятой в конце придаточного

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +При этом перегрузки, куда можно просто передать вектор не существовало.
не хватает запятой в конце придаточного

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +приводило к тому, что нужно было добавлять много дополнительных SFINAE проверок, если этого не делать, они начинают конфликтовать между собой.
это длиное предложение явно стоит разбить

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +приводило к тому, что нужно было добавлять много дополнительных SFINAE проверок, если этого не делать, они начинают конфликтовать между собой.
зачем убрал ссылку на пример? я в этом смысле вообще не очень понимаю смысла этого PR, он привносит не очень много нового, зато зачем-то сильно переваривает старое (и далеко не всегда становится лучше)

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Опыт использования стандартных алгоритмов показал, что от них ещё хочется какие-то вещи, и многие из них откладывались из-за того,
какие вещи?

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +когда в языке появились концепты -- алгоритмы стандартной библиотеки переделали.
`&mdash;`

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +когда в языке появились концепты -- алгоритмы стандартной библиотеки переделали.
не вижу ни одного преимущества новой формулировки по сравнению со старой

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> -P.S.: На лекции был пример реализации подсчета и сортировки слов по частоте вхождения в виде 6строчника на баше и 10страничной реализации Кнута на Паскале.
Почему считаешь, что эти абзацы лишние?

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Помимо алгоритмов с ренджами в стандарт вошли *views*. Например, мы можем
оборот с "помимо" в начале &mdash; обособляется

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +    }
зачем лишний уровень табуляции?

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +В первом приближении можно думать, что вьюхи -- это легковесные объекты, которые на что-то ссылаются и имеют специальные свойства, т.е. они не копируют внутрь себя ничего (обычно).
`&mdash;`, больше повторять не буду

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Что такое [`std::ranges::range`](https://en.cppreference.com/w/cpp/ranges/range)? Всё что угодно, если у него определены операции `begin(r)`, `end(r)`.
у него -> для него

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +[`std::ranges::view`](https://en.cppreference.com/w/cpp/ranges/view) -- Это `range`, она *movable* за `O(1)` и имеет ещё некоторое количество семантических ограничений. Для того чтобы сказать, что кл
давай не будем обращаться к `view` в женском роде

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +opt-in, который назывался `enable view`.
в смысле "существовал"? больше нет?

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +opt-in, который назывался `enable view`.
тоже не вижу преимуществ над предыдущей формулировкой, наоборот некоторая информация безвозвратно утеряна, а какая-то потерялась под менее понятными формулировками

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Примеры `range`, которые не являются `view`: `vector, array`.
давай в кавычки брать отдельные токены, а не перечисление

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Он работает следующим образом: `filter`, `transform` они принимают вьюху и возвращают вьюху. А если мы в начале передали не вьюху,
> `filter`, `transform` они принимают вьюху

это грамматически некорректное предложение

также предлагаю воздержаться от столь активного использования англицизма "вьюха"

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +3. (*) Если `r` -- *rvalue*, то возвращается `owning_view<R>` (вьюха, которая хранит сам объект). Со звёздочкой, потому что появилось не сразу вместе с std::ranges, а позже.
уточни, когда появилось, и как оно работало для rvalue до его появления

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +стали называть `sentinel`. Проверка на конец спрятана в операторе сравнения у `sentinel`. И это позволяет нам иметь, например, бесконечные ренжи:
это точно должно быть одним таким большим абзацем?

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +В C++03 существовали такие "ренжи" (пара итераторв), размера, которого мы не знаем на перёд (потенциально, он может быть бесконечным).
"наперёд" слитно

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Например, для `std::istream, std::regex_iterator`. В их реализации от того, что `begin` и `end` имеют один и тот же тип ничего не зависит.
явно не хватает запятой

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Например, для `std::istream, std::regex_iterator`. В их реализации от того, что `begin` и `end` имеют один и тот же тип ничего не зависит.
утеряна информационная нагрузка, присутствующая в предыдущей версии, стало менее понятно

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
что "это"?

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
нет такого итератора

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
некрасивое предложение, две части, и обе начинаются с "но" (="однако")

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +Хотелось бы ослабить это ограничение, многим алгоритмам не нужно, чтобы `begin` и `end` были одинакового типа.
вместо запятой здесь лучше двоеточие

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +В C++ ranges эту штуку немного поменяли, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
вместо запятой здесь лучше двоеточие

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +стали называть `sentinel`. Проверка на конец спрятана в операторе сравнения у `sentinel`. И это позволяет нам иметь, например, бесконечные ренжи:
лучше: "в операторе сравнения между итератором и `sentinel`"

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> +```
лишняя табуляция

2024-03-30 09:34 UTC, dedlocc commented on src/29_ranges.md
> -[`unreachable_sentinel`](https://en.cppreference.com/w/cpp/iterator/unreachable_sentinel_t).
куда это делось?

2024-03-30 12:56 UTC, brokenken commented on src/29_ranges.md
> +если нужно сортировать некоторый подотрезок, она нам подходит.
Исправил это.

2024-03-30 12:56 UTC, brokenken commented on src/29_ranges.md
> +А функция, которая принимает вектор целиком более частный случай.
Поставил запятую.

2024-03-30 12:57 UTC, brokenken commented on src/29_ranges.md
> +При этом перегрузки, куда можно просто передать вектор не существовало.
Поставил запятую.

2024-03-30 12:57 UTC, brokenken commented on src/29_ranges.md
> +приводило к тому, что нужно было добавлять много дополнительных SFINAE проверок, если этого не делать, они начинают конфликтовать между собой.
Разбил предложение на несколько частей.

2024-03-30 12:57 UTC, brokenken commented on src/29_ranges.md
> +приводило к тому, что нужно было добавлять много дополнительных SFINAE проверок, если этого не делать, они начинают конфликтовать между собой.
Добавил ссылку на пример.

2024-03-30 12:58 UTC, brokenken commented on src/29_ranges.md
> +Опыт использования стандартных алгоритмов показал, что от них ещё хочется какие-то вещи, и многие из них откладывались из-за того,
Добавил пример.

2024-03-30 12:58 UTC, brokenken commented on src/29_ranges.md
> +когда в языке появились концепты -- алгоритмы стандартной библиотеки переделали.
Заменил здесь и далее.

2024-03-30 12:58 UTC, brokenken commented on src/29_ranges.md
> +когда в языке появились концепты -- алгоритмы стандартной библиотеки переделали.
Вернул старую формулировку.

2024-03-30 12:58 UTC, brokenken commented on src/29_ranges.md
> -P.S.: На лекции был пример реализации подсчета и сортировки слов по частоте вхождения в виде 6строчника на баше и 10страничной реализации Кнута на Паскале.
Вернул эти абзацы.

2024-03-30 12:58 UTC, brokenken commented on src/29_ranges.md
> +Помимо алгоритмов с ренджами в стандарт вошли *views*. Например, мы можем
Выделил запятой данный оборот.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +    }
Убрал лишнюю табуляцию.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +В первом приближении можно думать, что вьюхи -- это легковесные объекты, которые на что-то ссылаются и имеют специальные свойства, т.е. они не копируют внутрь себя ничего (обычно).
Исправил.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +Что такое [`std::ranges::range`](https://en.cppreference.com/w/cpp/ranges/range)? Всё что угодно, если у него определены операции `begin(r)`, `end(r)`.
Исправил.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +[`std::ranges::view`](https://en.cppreference.com/w/cpp/ranges/view) -- Это `range`, она *movable* за `O(1)` и имеет ещё некоторое количество семантических ограничений. Для того чтобы сказать, что кл
Исправил.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +opt-in, который назывался `enable view`.
Изменил на существует.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +opt-in, который назывался `enable view`.
Вернул частично старую формулировку.

2024-03-30 12:59 UTC, brokenken commented on src/29_ranges.md
> +Примеры `range`, которые не являются `view`: `vector, array`.
Исправил.

2024-03-30 13:00 UTC, brokenken commented on src/29_ranges.md
> +Он работает следующим образом: `filter`, `transform` они принимают вьюху и возвращают вьюху. А если мы в начале передали не вьюху,
Исправил предложение, заменил вьюха на `view`.

2024-03-30 13:00 UTC, brokenken commented on src/29_ranges.md
> +3. (*) Если `r` -- *rvalue*, то возвращается `owning_view<R>` (вьюха, которая хранит сам объект). Со звёздочкой, потому что появилось не сразу вместе с std::ranges, а позже.
Добавил уточнение и принцип работы до появления.

2024-03-30 13:00 UTC, brokenken commented on src/29_ranges.md
> +стали называть `sentinel`. Проверка на конец спрятана в операторе сравнения у `sentinel`. И это позволяет нам иметь, например, бесконечные ренжи:
Разбил на несколько абзацев.

2024-03-30 13:00 UTC, brokenken commented on src/29_ranges.md
> +В C++03 существовали такие "ренжи" (пара итераторв), размера, которого мы не знаем на перёд (потенциально, он может быть бесконечным).
Исправил.

2024-03-30 13:01 UTC, brokenken commented on src/29_ranges.md
> +Например, для `std::istream, std::regex_iterator`. В их реализации от того, что `begin` и `end` имеют один и тот же тип ничего не зависит.
Исправил.

2024-03-30 13:01 UTC, brokenken commented on src/29_ranges.md
> +Например, для `std::istream, std::regex_iterator`. В их реализации от того, что `begin` и `end` имеют один и тот же тип ничего не зависит.
Вернул информацию из старой версии.

2024-03-30 13:02 UTC, brokenken commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
То, что `begin` и `end` имеют одинаковый тип из предыдущего предложения.

2024-03-30 13:02 UTC, brokenken commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
Удалил это предложение.

2024-03-30 13:03 UTC, brokenken commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
Удалил второе предложение.

2024-03-30 13:03 UTC, brokenken commented on src/29_ranges.md
> +Хотелось бы ослабить это ограничение, многим алгоритмам не нужно, чтобы `begin` и `end` были одинакового типа.
Перефразировал это предложение.

2024-03-30 13:03 UTC, brokenken commented on src/29_ranges.md
> +В C++ ranges эту штуку немного поменяли, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
Перефразировал это предложение.

2024-03-30 13:04 UTC, brokenken commented on src/29_ranges.md
> +стали называть `sentinel`. Проверка на конец спрятана в операторе сравнения у `sentinel`. И это позволяет нам иметь, например, бесконечные ренжи:
Исправил.

2024-03-30 13:04 UTC, brokenken commented on src/29_ranges.md
> +```
Исправил.

2024-03-30 13:04 UTC, brokenken commented on src/29_ranges.md
> -[`unreachable_sentinel`](https://en.cppreference.com/w/cpp/iterator/unreachable_sentinel_t).
Добавил.

2024-03-30 17:52 UTC, dedlocc requested changes

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +когда в языке появились концепты &mdash; алгоритмы стандартной библиотеки переделали.
https://github.com/CPP-KT/cpp-notes/pull/46#discussion_r1545242245

не везде поправил

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +При этом короткой формы, которая принимала просто какой-то контейнер, не было.
зачем здесь пробел в конце? и это много где так

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +если нужно сортировать некоторый подотрезок, она нам подходит.
здесь даже лучше тире

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +Примеры `range`, которые не являются `view`: `vector, array`.
одну строку исправил, другую нет

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +Со звёздочкой, потому что появилось только в C++20 DR (Defect Report) [P2415](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2415r2.html).
чтобы не привязываться к конкретно этому урлу, хорошая практика такие ссылки оформлять в виде `https://wg21.link/P2415`

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +В C++03 существовали такие "ренжи" (пара итераторов), размера, которого мы не знаем наперёд (потенциально, он может быть бесконечным), например, `std::istream, std::regex_iterator`.
здесь тоже перечисление в кавычках

при том что в оригинале было правильно

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
почему бы не написать явно? например вместо
> В их реализации от того, что `begin` и `end` имеют один и тот же тип, ничего не зависит.
Но это требуют практически все стандартные алгоритмы. Из-за этого приходится делать разные проверки, например `is_end()` и т.п.

написать:
> Для них не совершенно не принципиально, чтобы `begin()` и `end()` имели один и тот же тип. Наоборот, это может усложнять код всякими проверками вида `is_end()`. Однако практически все стандартные алгоритмы требуют, чтобы итераторы по типу совпадали.

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +Хотелось бы ослабить это ограничение, многим алгоритмам не нужно, чтобы `begin` и `end` были одинакового типа.
ничего не поменялось в предложении, к которому этот комментарий относится (последнему из отображаемых)

например предлагаю формулировку:
> Хотелось бы ослабить это ограничение: многие алгоритмы могли бы спокойно работать, даже если `begin` и `end` имеют различные типы.

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +В C++ ranges эту штуку немного поменяли, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
предложение всё ещё в силе, просто запятая немного сдвинулась

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +В C++ ranges разрешили иметь разные типы начала и конца, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
всё так же

2024-03-30 17:52 UTC, dedlocc commented on src/29_ranges.md
> +Про данный тип окончания, можно прочитать здесь: [unreachable_sentinel_t](https://en.cppreference.com/w/cpp/iterator/unreachable_sentinel_t).
запятая лишняя

2024-03-30 18:27 UTC, brokenken commented on src/29_ranges.md
> +если нужно сортировать некоторый подотрезок, она нам подходит.
Заменил.

2024-03-30 18:27 UTC, brokenken commented on src/29_ranges.md
> +Примеры `range`, которые не являются `view`: `vector, array`.
Исправил.

2024-03-30 18:27 UTC, brokenken commented on src/29_ranges.md
> +Но это требуют практически все стандартные алгоритмы, однако когда мы реализуем, например, `std::isstream_iterator`, это дополнительная сложность.
Заменил на второй вариант.

2024-03-30 18:27 UTC, brokenken commented on src/29_ranges.md
> +Хотелось бы ослабить это ограничение, многим алгоритмам не нужно, чтобы `begin` и `end` были одинакового типа.
Использовал эту формулировку.

2024-03-30 18:28 UTC, brokenken commented on src/29_ranges.md
> +В C++ ranges эту штуку немного поменяли, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
Поставил запятую.

2024-03-30 18:28 UTC, brokenken commented on src/29_ranges.md
> +когда в языке появились концепты &mdash; алгоритмы стандартной библиотеки переделали.
Исправил.

2024-03-30 18:28 UTC, brokenken commented on src/29_ranges.md
> +При этом короткой формы, которая принимала просто какой-то контейнер, не было.
Убрал все пробелы на конце.

2024-03-30 18:28 UTC, brokenken commented on src/29_ranges.md
> +Со звёздочкой, потому что появилось только в C++20 DR (Defect Report) [P2415](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2415r2.html).
Изменил ссылку.

2024-03-30 18:28 UTC, brokenken commented on src/29_ranges.md
> +В C++03 существовали такие "ренжи" (пара итераторов), размера, которого мы не знаем наперёд (потенциально, он может быть бесконечным), например, `std::istream, std::regex_iterator`.
Исправил.

2024-03-30 18:29 UTC, brokenken commented on src/29_ranges.md
> +В C++ ranges разрешили иметь разные типы начала и конца, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
Если это комментарий про перенос предложения, то исправил.

2024-03-30 18:29 UTC, brokenken commented on src/29_ranges.md
> +Про данный тип окончания, можно прочитать здесь: [unreachable_sentinel_t](https://en.cppreference.com/w/cpp/iterator/unreachable_sentinel_t).
Убрал.

2024-03-31 10:21 UTC, dedlocc requested changes

2024-03-31 10:21 UTC, dedlocc commented on src/29_ranges.md
> +если нужно сортировать некоторый подотрезок, она нам подходит.
ну блин, не там...

кстати слово "она" явно лишнее

> Почему так было сделано? Идея такая: форма, которая принимает два итератора, более общая, и если нужно сортировать некоторый подотрезок, она нам подходит.
> А функция, которая принимает вектор целиком &mdash; более частный случай.

2024-03-31 10:21 UTC, dedlocc commented on src/29_ranges.md
> +В C++ ranges разрешили иметь разные типы начала и конца, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
это комментарий про написание "всё так же"

2024-03-31 10:29 UTC, brokenken commented on src/29_ranges.md
> +В C++ ranges разрешили иметь разные типы начала и конца, в качестве `begin` передаётся всё также итератор, а вот объект, который показывает, где конец,
Исправил.

2024-03-31 10:30 UTC, brokenken commented on src/29_ranges.md
> +если нужно сортировать некоторый подотрезок, она нам подходит.
Удалил слово она и поставил тире.

2024-03-31 10:31 UTC, dedlocc approved these changes

2024-03-31 10:31 UTC, dedlocc commented on src/29_ranges.md
> +А функция, которая принимает вектор целиком &mdash; более частный случай.
```suggestion
Почему так было сделано? Идея такая: форма, которая принимает два итератора более общая, и если нужно сортировать некоторый подотрезок, она нам подходит.
А функция, которая принимает вектор целиком &mdash; более частный случай.
```

2024-03-31 10:32 UTC, merged